name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: python-microservices-with-grpc
      run: docker build . --file marketplace/Dockerfile --tag marketplace:$(date +%s); docker build . --file recommendations/Dockerfile --tag recommendations:$(date +%s)
